### ISSUE TITLE
Add question for StS Yes or No

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/StSTemplates#1]
2.	It is critical to the US&R system to have structure hazard markings (three white boxes) gathered by qualified engineers especially for earthquake/blast events 
a.	I think it is possible non-engineers may need to complete this task so a radial button indicating STS or not STS is needed
b.	A symbol (three white boxes – system trains with these) needs to accompany these surveys and appear on the shared system apps

From Dave Weber

**Comment by oviera-napsg** [comment]
Question was added.  It is currently (13 March 2024) a required field in the Field Maps form.  Closing this.
